version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - my-redis/:/data
    networks: 
      - mynet
  mongodb:
    image: mongo
    volumes:
      - my-mongodb/:/data/db
    ports:
      - "27017:27017"
    networks: 
      - mynet
  blog-api:
    image: blog-api:v0.0.1
    volumes:
      - my-log/:/usr/src/app/log
    env_file: ./.env
    environment:
      - DB_HOST=mongodb
      - REDIS_HOST=redis
    depends_on:
      - redis
      - mongodb
    networks: 
      - mynet
    ports:
      - "3400:3400"

networks: 
  mynet:
    driver: bridge

volumes:
  my-redis:
  my-mongodb:
  my-log: