version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - my-redis/:/data
    networks: 
      - mynet
  mongodb:
    image: mongo
    volumes:
      - my-mongodb/:/data/db
    ports:
      - "27017:27017"
    networks: 
      - mynet

networks: 
  mynet:
    driver: bridge

volumes:
  my-redis:
  my-mongodb: